-- Alter
ALTER TABLE T_CUSTOMER ADD COLUMN creditcardnumber VARCHAR(25);
ALTER TABLE T_CUSTOMER ADD COLUMN creditcardtype VARCHAR(25);
ALTER TABLE T_CUSTOMER ADD COLUMN creditcardexpirydate VARCHAR(10);
ALTER TABLE T_CUSTOMER ADD COLUMN email VARCHAR(255);
